Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleApp.Controllers
{
    public class BaseController : Controller
    {
        //
        // GET: /Base/

        protected override void OnActionExecuting(ActionExecutingContext filterContext)
        {
            base.OnActionExecuting(filterContext);
            if (Session["userid"] == null)
            {
                Response.Redirect("/Login");
            }
        }

    }
}

Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Controllers/EmployeeController.cs
using SampleEntity;
using SampleRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleApp.Controllers
{
    public class EmployeeController : BaseController
    {
        //
        // GET: /Empployee/
        EmployeeRepo erepo = new EmployeeRepo();
        public ActionResult Index()
        {
            return View(erepo.GetAll());
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Employee e)
        {
            if (ModelState.IsValid)
            {
                erepo.Insert(e);
                return RedirectToAction("Index");
            }
            else
            {
                return View(e);
            }
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Employee emp = erepo.Get(id);
            return View(emp);
        }
        [HttpPost]
        public ActionResult Edit(Employee emp)
        {
            if (ModelState.IsValid)
            {
                erepo.Update(emp);
                return RedirectToAction("Index");
            }
            else
            {
                return View(emp);
            }
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            Employee emp = erepo.Get(id);
            return View(emp);
        }
        [HttpPost][ActionName("Delete")]
        public ActionResult Delete_Confirmed(int id)
        {
            Employee emp = erepo.Get(id);
            erepo.Delete(emp);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Details(int id)
        {
            Employee e = erepo.Get(id);
            return View(e);
        }
    }
}

Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Controllers/HomeController.cs
using SampleRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleApp.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/
        
        public ActionResult Index()
        {
            SampleDBContext context = new SampleDBContext();
            context.Users.ToList();
            return View();
        }

    }
}

Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Controllers/LoginController.cs
using SampleEntity;
using SampleRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleApp.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/

        SampleDBContext context = new SampleDBContext();
        [HttpGet]
        public ActionResult Index()
        {
            return View(); 
        }
        [HttpPost]
        public ActionResult Index(User user)
        {

            User validUser = context.Users.SingleOrDefault(u => u.UserId == user.UserId && u.Password == user.Password);
            if (validUser == null)
            {
                TempData["error"] = "Invalid User or Password";
                return RedirectToAction("Index");
            }
            else
            {
                Session["userid"] = validUser.UserId;
                Session["type"] = validUser.Type;
                if (validUser.Type.Equals("customer"))
                {
                    return RedirectToAction("Index", "Customer");
                }
                else
                {
                    return RedirectToAction("Index", "Employee");
                }
            }
        }
        public ActionResult Logout()
        {
            Session["userid"] = null;
            Session["type"] = null;
            return RedirectToAction("Index");
        }

    }
}

Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Controllers/RegistrationController.cs
using SampleEntity;
using SampleRepository;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleApp.Controllers
{
    public class RegistrationController : Controller
    {
        //
        // GET: /Registration/
        CustomerRepo crepo = new CustomerRepo();

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Customer c)
        {
            if (ModelState.IsValid)
            {
                crepo.Insert(c);
                TempData["id"] = c.UserId;
                return RedirectToAction("Index", "Login");
            }
            else
            {
                return View(c);
            }
        }

    }
}

Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Views/Employee/Create.cshtml
@model SampleEntity.Employee

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>Employee</legend>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.EmployeeName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.EmployeeName)
                @Html.ValidationMessageFor(model => model.EmployeeName)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.PhoneNumber)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Salary)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Salary)
                @Html.ValidationMessageFor(model => model.Salary)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Password)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Type)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>
    
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")<br />
         @Html.ActionLink("Logout", "Logout", "Login")
    </div>
</body>
</html>

Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Views/Employee/Delete.cshtml
@model SampleEntity.Employee

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <fieldset>
        <legend>Employee</legend>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.EmployeeName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.EmployeeName)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.PhoneNumber)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.PhoneNumber)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.Salary)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Salary)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.Type)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Type)
        </div>
    </fieldset>
    @using (Html.BeginForm()) {
        <p>
            <input type="submit" value="Delete" /> |
            @Html.ActionLink("Back to List", "Index")
        </p>
    }
     @Html.ActionLink("Logout", "Logout", "Login")

</body>
</html>

Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Views/Employee/Details.cshtml
@model SampleEntity.Employee

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <fieldset>
        <legend>Employee</legend>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.EmployeeName)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.EmployeeName)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.PhoneNumber)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.PhoneNumber)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.Salary)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Salary)
        </div>
    
        <div class="display-label">
             @Html.DisplayNameFor(model => model.Type)
        </div>
        <div class="display-field">
            @Html.DisplayFor(model => model.Type)
        </div>
    </fieldset>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id=Model.UserId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
     @Html.ActionLink("Logout", "Logout", "Login")
</body>
</html>

Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Views/Employee/Edit.cshtml
@model SampleEntity.Employee

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm()) {
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>Employee</legend>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.EmployeeName)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.EmployeeName)
                @Html.ValidationMessageFor(model => model.EmployeeName)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.PhoneNumber)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.PhoneNumber)
                @Html.ValidationMessageFor(model => model.PhoneNumber)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Salary)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Salary)
                @Html.ValidationMessageFor(model => model.Salary)
            </div>
    
            @Html.HiddenFor(model => model.UserId)
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Password)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Password)
                @Html.ValidationMessageFor(model => model.Password)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Type)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Type)
                @Html.ValidationMessageFor(model => model.Type)
            </div>
    
            <p>
                <input type="submit" value="Save" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")<br />
         @Html.ActionLink("Logout", "Logout", "Login")
    </div>
</body>
</html>

Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Views/Employee/Index.cshtml
@model IEnumerable<SampleEntity.Employee>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.EmployeeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PhoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Type)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EmployeeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.UserId }) |
                @Html.ActionLink("Details", "Details", new { id=item.UserId }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.UserId })
            </td>
        </tr>
    }
    </table>
    @Html.ActionLink("Logout", "Logout", "Login")
</body>
</html>

Sample Code By Faculty/sample management system/samplemanagementsystem/sampleapp/Views/Home/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div>
        @Html.ActionLink("Click Here Login", "Index", "Login")
        @Html.ActionLink("Customer Registration", "Create", "Registration")
    </div>
</body>
</html>